[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
remappings = ["forge-std/=node_modules/forge-std/src/"]
fs_permissions = [
  { access = "read-write", path = "deployed-counter-address.txt" },
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
